// <auto-generated />
using System;
using Kimo.ZLApp.Infrastructure.Common.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kimo.ZLApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260424204245_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kimo.ZLApp.Domain.Locations.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Kimo.ZLApp.Domain.WeatherForecasts.Forecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("LocationId");

                    b.ToTable("Forecast");
                });

            modelBuilder.Entity("Kimo.ZLApp.Domain.WeatherForecasts.Forecast", b =>
                {
                    b.HasOne("Kimo.ZLApp.Domain.Locations.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Kimo.ZLApp.Domain.WeatherForecasts.PrecipitationEntry", "Precipitations", b1 =>
                        {
                            b1.Property<int>("ForecastId")
                                .HasColumnType("int");

                            b1.Property<int>("Hour")
                                .HasColumnType("int");

                            b1.Property<double>("Value")
                                .HasColumnType("float");

                            b1.HasKey("ForecastId", "Hour");

                            b1.ToTable("PrecipitationEntry");

                            b1.WithOwner()
                                .HasForeignKey("ForecastId");
                        });

                    b.OwnsOne("Kimo.ZLApp.Domain.WeatherForecasts.TemperatureData", "TemperatureData", b1 =>
                        {
                            b1.Property<int>("ForecastId")
                                .HasColumnType("int");

                            b1.HasKey("ForecastId");

                            b1.ToTable("Forecast");

                            b1.WithOwner()
                                .HasForeignKey("ForecastId");

                            b1.OwnsMany("Kimo.ZLApp.Domain.WeatherForecasts.TemperatureDataEntry", "Temperatures", b2 =>
                                {
                                    b2.Property<int>("ForecastId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Hour")
                                        .HasColumnType("int");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float");

                                    b2.HasKey("ForecastId", "Hour");

                                    b2.ToTable("TemperatureDataEntry");

                                    b2.WithOwner()
                                        .HasForeignKey("ForecastId");
                                });

                            b1.Navigation("Temperatures");
                        });

                    b.Navigation("Location");

                    b.Navigation("Precipitations");

                    b.Navigation("TemperatureData")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
